baseURL = "/"
languageCode = "en-us"
title = "FETCH₄"
themesDir = "themes"
theme = "hugo-hero-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"

[params]
  google_analytics_id=""

  [params.logo]
    mobile = "images/logo.png"
    mobile_height = "36px"
    mobile_width = "36px"
    desktop = "images/logo.png"
    desktop_height = "29px"
    desktop_width = "217px"
    alt = "Hugo Hero"

  [params.homepage_meta_tags]
    meta_description = "FETCH₄ - Fate, Emissions, and Transport of CH₄ : An international collaboration of scientists focused on improving our understanding of the past and modern methane cycle."
    meta_og_title = "FETCH₄ "
    meta_og_type = "website"
    meta_og_url = "https://fetch4.github.io/"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "FETCH₄ - Fate, Emissions, and Transport of CH₄ : An international collaboration of scientists focused on improving our understanding of the past and modern methane cycle."
    meta_twitter_card = "summary"
    meta_twitter_site = "@so_fetch4"
    meta_twitter_creator = "@so_fetch4"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

[[menu.main]]
	name = "Jobs"
	url = "/jobs/"
    weight = 2

[[menu.main]]
	name = "Team"
	url = "/team/"
    weight = 3

# Enable these below later

#[[menu.main]]
#    name = "Research"
#    url = "/research/"
#    weight = 4

# [[menu.main]]
#     name = "Code"
#     url = "/code/"
#     weight = 5

# [[menu.main]]
#     name = "Publications"
#     url = "/publications/"
#     weight = 6

# [[menu.main]]
#     name = "News"
#     url = "/news/"
#     weight = 7

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
